### ISSUE TITLE
Cleanup Utility List

### ISSUE THREAD

**Issue by vinomaster** [trustoverip/utility-foundry-wg#17]
It is unclear for some of the entires on our list which ones are actual active public identity utilities. 
We need to establish some criteria for entries.

The following need to be pruned:

1.  [govdigital](https://www.govdigital.de)  as it is our understanding that the stakeholders will be using idUnion.
2. [eco - Association of the Internet Industry](https://international.eco.de)   as it is our understanding that the stakeholders will be using idUnion.
3. [KochiOrgBook](https://github.com/hyperledgerkochi/KOBman) from Wipro, Kochi University (CUSAT), Kerala Blockchain Academy (KBA) *is not* a public identity utility but a tool that would leverage one. 

Leveraging our Workflow Swim-lanes, entries need to specify where they are in the project lifecycle and MUST minimally be at the **Convene** stage.

**Comment by vinomaster** [comment]
An updated from @kudrixD:

1. **govdigital** - not IDunion at all - dedicated legal entity of ONLY public sector players in Germany - Planning their own HL Indy network. If and when they get to the **Convene** phase we can list them if they so desire.
2. **eco** - will be supporting IDunion.

**Comment by panickervinod** [comment]
@vinomaster The link for KochiOrgBook  is to KOBman and not to KochiOrgBook.  Hence the confusion.
