### ISSUE TITLE
Project Definition

### ISSUE THREAD

**Issue by stevenmilstein** [trustoverip/utility-foundry-wg#4]
According to [What is Project Management | PMI](https://www.pmi.org/about/learn-about-pmi/what-is-project-management#:~:text=A%20project%20is%20temporary%20in,therefore%20defined%20scope%20and%20resources.&text=Project%20management%2C%20then%2C%20is%20the,to%20meet%20the%20project%20requirements)

> A project is temporary in that it has a defined beginning and end in time, and therefore defined scope and resources.

Perhaps **"Service"** could replace **"Project"** since a Utility, under normal conditions, is providing an on-going service.

**Comment by vinomaster** [comment]
Steve where is the change you are requesting to be made? Are you referring to the "Term" Project as it is used across the foundation? If so please close this issue and open one against [CTWG](https://github.com/trustoverip/concepts-and-terminology-wg/issues) BUT please make note of issues 18-21.

**Comment by vinomaster** [comment]
@stevenmilstein can you please open a term issue against CTWG and close this via a link to new issue?

**Comment by vinomaster** [comment]
@stevenmilstein Requesting again for this issue to be closed with redirection to a CTWG issue.

**Comment by stevenmilstein** [comment]
Moved to https://github.com/trustoverip/concepts-and-terminology-wg/issues/33
